// Catálogo de produtos — SEM preço, parcelamento ou desconto.
// Catálogo completo: Titan, Monster, Monster Select e as 10 linhas do PRO
// (Esteiras, Bikes, Elípticos, Escada e Remo, Hammer Force, Alfa, Classic,
// Plate Load, Titanium, Station, Acessórios).
const produtos = [

  // ── LINHA TITAN ──────────────────────────────────────
  { id: 1, nome: "Supino Reto", categoria: "Titan", foto: "assets/images/produtos/titan/y905.jpg" },
  { id: 2, nome: "Supino Declinado", categoria: "Titan", foto: "assets/images/produtos/titan/y910.jpg" },
  { id: 3, nome: "Supino Inclinado", categoria: "Titan", foto: "assets/images/produtos/titan/y915.jpg" },
  { id: 4, nome: "Puxada Alta", categoria: "Titan", foto: "assets/images/produtos/titan/y920.jpg" },
  { id: 5, nome: "Remada Baixa", categoria: "Titan", foto: "assets/images/produtos/titan/y925.jpg" },
  { id: 6, nome: "Remada", categoria: "Titan", foto: "assets/images/produtos/titan/y930.jpg" },
  { id: 7, nome: "Desenvolvimento de Ombro", categoria: "Titan", foto: "assets/images/produtos/titan/y935.jpg" },
  { id: 8, nome: "Glúteo", categoria: "Titan", foto: "assets/images/produtos/titan/y940.jpg" },
  { id: 9, nome: "Cadeira Extensora", categoria: "Titan", foto: "assets/images/produtos/titan/y960.jpg" },
  { id: 10, nome: "Tríceps Paralela Anilhado", categoria: "Titan", foto: "assets/images/produtos/titan/y965.jpg" },
  { id: 11, nome: "Scott Anilhado", categoria: "Titan", foto: "assets/images/produtos/titan/y970.jpg" },

  // ── LINHA MONSTER ────────────────────────────────────
  { id: 12, nome: "Super Horizontal Multi Press", categoria: "Monster", foto: "assets/images/produtos/monster/pt01.jpg" },
  { id: 13, nome: "Super Vertical Chest Press", categoria: "Monster", foto: "assets/images/produtos/monster/pt01a.jpg" },
  { id: 14, nome: "Super Rowing", categoria: "Monster", foto: "assets/images/produtos/monster/pt04.jpg" },
  { id: 15, nome: "T-Bar Row", categoria: "Monster", foto: "assets/images/produtos/monster/pt04a.jpg" },
  { id: 16, nome: "French Press Machine", categoria: "Monster", foto: "assets/images/produtos/monster/pt07.jpg" },
  { id: 17, nome: "Super Power Row", categoria: "Monster", foto: "assets/images/produtos/monster/pt10.jpg" },
  { id: 18, nome: "Super Lat Machine Convergent", categoria: "Monster", foto: "assets/images/produtos/monster/pt12.jpg" },
  { id: 19, nome: "Super High Row", categoria: "Monster", foto: "assets/images/produtos/monster/pt12c.jpg" },
  { id: 20, nome: "Super Pendulum Squat", categoria: "Monster", foto: "assets/images/produtos/monster/pt13.jpg" },
  { id: 21, nome: "Super Leg Press 45°", categoria: "Monster", foto: "assets/images/produtos/monster/pt15a.jpg" },
  { id: 22, nome: "Standing Abductor", categoria: "Monster", foto: "assets/images/produtos/monster/pt17.jpg" },
  { id: 23, nome: "Power Smith Machine Dual System", categoria: "Monster", foto: "assets/images/produtos/monster/pt19.jpg" },
  { id: 24, nome: "Vertical Leg Press", categoria: "Monster", foto: "assets/images/produtos/monster/pt20.jpg" },
  { id: 25, nome: "Hip Thrust", categoria: "Monster", foto: "assets/images/produtos/monster/pt21.jpg" },
  { id: 26, nome: "Shoulder Press", categoria: "Monster", foto: "assets/images/produtos/monster/bh03.jpg" },
  { id: 27, nome: "Standing Hip Thrust", categoria: "Monster", foto: "assets/images/produtos/monster/bh11.jpg" },
  { id: 28, nome: "Leg Extension", categoria: "Monster", foto: "assets/images/produtos/monster/bh14.jpg" },
  { id: 29, nome: "Chest Press", categoria: "Monster", foto: "assets/images/produtos/monster/bh01a.jpg" },
  { id: 30, nome: "Lat Pull Down", categoria: "Monster", foto: "assets/images/produtos/monster/bh12b.jpg" },

  // ── LINHA MONSTER SELECT ─────────────────────────────
  { id: 31, nome: "Iso-Lateral Super Incline Press", categoria: "Monster Select", foto: "assets/images/produtos/monster/met102.jpg" },
  { id: 32, nome: "Kneeling Leg Curl", categoria: "Monster Select", foto: "assets/images/produtos/monster/met103.jpg" },
  { id: 33, nome: "Bicep Trainer", categoria: "Monster Select", foto: "assets/images/produtos/monster/met105.jpg" },
  { id: 34, nome: "Side Arm Lift Trainer", categoria: "Monster Select", foto: "assets/images/produtos/monster/met106.jpg" },
  { id: 35, nome: "Reloaded Iso Flat Press", categoria: "Monster Select", foto: "assets/images/produtos/monster/met118.jpg" },
  { id: 36, nome: "Arm Down Back Muscle Training", categoria: "Monster Select", foto: "assets/images/produtos/monster/met120.jpg" },

  // ── PRO · ESTEIRAS ───────────────────────────────────
  { id: 37, nome: "ECK", categoria: "Esteiras", foto: "assets/images/produtos/pro/eck.jpg" },
  { id: 38, nome: "KX10000i", categoria: "Esteiras", foto: "assets/images/produtos/pro/kx10000i.jpg" },
  { id: 39, nome: "KX9000i", categoria: "Esteiras", foto: "assets/images/produtos/pro/kx9000i.jpg" },
  { id: 40, nome: "T-PRO Run", categoria: "Esteiras", foto: "assets/images/produtos/pro/t_pro_run.jpg" },
  { id: 41, nome: "PRO Run", categoria: "Esteiras", foto: "assets/images/produtos/pro/pro_run.jpg" },
  { id: 42, nome: "KX8600", categoria: "Esteiras", foto: "assets/images/produtos/pro/kx8600.jpg" },
  { id: 43, nome: "KX8500i", categoria: "Esteiras", foto: "assets/images/produtos/pro/kx8500i.jpg" },

  // ── PRO · BIKES ──────────────────────────────────────
  { id: 44, nome: "F13", categoria: "Bikes", foto: "assets/images/produtos/pro/f13.jpg" },
  { id: 45, nome: "MS4000i", categoria: "Bikes", foto: "assets/images/produtos/pro/ms4000i.jpg" },
  { id: 46, nome: "MS2000", categoria: "Bikes", foto: "assets/images/produtos/pro/ms2000.jpg" },
  { id: 47, nome: "ARXi", categoria: "Bikes", foto: "assets/images/produtos/pro/arxi.jpg" },
  { id: 48, nome: "KV10.0", categoria: "Bikes", foto: "assets/images/produtos/pro/kv10_0.jpg" },
  { id: 49, nome: "KV9.8iX", categoria: "Bikes", foto: "assets/images/produtos/pro/kv9_8ix.jpg" },
  { id: 50, nome: "KR11.0", categoria: "Bikes", foto: "assets/images/produtos/pro/kr11_0.jpg" },
  { id: 51, nome: "KR9.9iX", categoria: "Bikes", foto: "assets/images/produtos/pro/kr9_9ix.jpg" },

  // ── PRO · ELÍPTICOS ──────────────────────────────────
  { id: 52, nome: "KE7.7", categoria: "Elípticos", foto: "assets/images/produtos/pro/ke7_7.jpg" },
  { id: 53, nome: "KE5.5", categoria: "Elípticos", foto: "assets/images/produtos/pro/ke5_5.jpg" },

  // ── PRO · ESCADA E REMO ──────────────────────────────
  { id: 54, nome: "T20.0", categoria: "Escada e Remo", foto: "assets/images/produtos/pro/t20_0.jpg" },
  { id: 55, nome: "KE19.0", categoria: "Escada e Remo", foto: "assets/images/produtos/pro/ke19_0.jpg" },
  { id: 56, nome: "KE17.0i", categoria: "Escada e Remo", foto: "assets/images/produtos/pro/ke17_0i.jpg" },
  { id: 57, nome: "WR200", categoria: "Escada e Remo", foto: "assets/images/produtos/pro/wr200.jpg" },

  // ── PRO · HAMMER FORCE ───────────────────────────────
  { id: 58, nome: "Supino Com Puxada", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_supino_com_puxada.jpg" },
  { id: 59, nome: "Remada Divergente", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_remada_divergente.jpg" },
  { id: 60, nome: "Puxada Frontal Invertida", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_puxada_frontal_invertida.jpg" },
  { id: 61, nome: "Puxada Alta", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_puxada_alta.jpg" },
  { id: 62, nome: "Supino Horizontal", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_supino_horizontal.jpg" },
  { id: 63, nome: "Remada Baixa", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_remada_baixa.jpg" },
  { id: 64, nome: "Remada", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_remada.jpg" },
  { id: 65, nome: "Desenvolvimento Gaiola", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_desenvolvimento_gaiola.jpg" },
  { id: 66, nome: "Supino Inclinado", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_supino_inclinado.jpg" },
  { id: 67, nome: "Supino Gaiola Declinado", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_supino_gaiola_declinado.jpg" },
  { id: 68, nome: "Pulldown", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_pulldown.jpg" },
  { id: 69, nome: "Tríceps Paralela", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_triceps_paralela.jpg" },
  { id: 70, nome: "Cadeira Extensora Unilateral", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_cadeira_extensora_unilateral.jpg" },
  { id: 71, nome: "Panturrilha Horizontal", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_panturrilha_horizontal.jpg" },
  { id: 72, nome: "Base Terrestre Gaiola", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_base_terrestre_gaiola.jpg" },
  { id: 73, nome: "Flexora em Pé Unilateral", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_flexora_em_pe_unilateral.jpg" },
  { id: 74, nome: "Abdominal Completo", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_abdominal_completo.jpg" },
  { id: 75, nome: "Super Agachamento", categoria: "Hammer Force", foto: "assets/images/produtos/pro/hf_super_agachamento.jpg" },

  // ── PRO · ALFA ───────────────────────────────────────
  { id: 76, nome: "Supino Máquina", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_supino_maquina.jpg" },
  { id: 77, nome: "Peitoral Peck Deck", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_peitoral_peck_deck.jpg" },
  { id: 78, nome: "Supino Inclinado", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_supino_inclinado.jpg" },
  { id: 79, nome: "Peitoral / Dorsal", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_peitoral_dorsal.jpg" },
  { id: 80, nome: "Desenvolvimento Ombro", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_desenvolvimento_ombro.jpg" },
  { id: 81, nome: "Remada Baixa", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_remada_baixa.jpg" },
  { id: 82, nome: "Puxador Costas", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_puxador_costas.jpg" },
  { id: 83, nome: "Remada", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_remada.jpg" },
  { id: 84, nome: "Scott Máquina", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_scott_maquina.jpg" },
  { id: 85, nome: "Tríceps", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_triceps.jpg" },
  { id: 86, nome: "Abdominal", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_abdominal.jpg" },
  { id: 87, nome: "Lombar", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_lombar.jpg" },
  { id: 88, nome: "Gráviton", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_graviton.jpg" },
  { id: 89, nome: "Leg Press", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_leg_press.jpg" },
  { id: 90, nome: "Cadeira Extensora", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_cadeira_extensora.jpg" },
  { id: 91, nome: "Cadeira Flexora", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_cadeira_flexora.jpg" },
  { id: 92, nome: "Mesa Flexora", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_mesa_flexora.jpg" },
  { id: 93, nome: "Abdutora", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_abdutora.jpg" },
  { id: 94, nome: "Adutora", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_adutora.jpg" },
  { id: 95, nome: "Glúteo", categoria: "Alfa", foto: "assets/images/produtos/pro/alfa_gluteo.jpg" },

  // ── PRO · CLASSIC ────────────────────────────────────
  { id: 96, nome: "Supino Máquina", categoria: "Classic", foto: "assets/images/produtos/pro/classic_supino_maquina.jpg" },
  { id: 97, nome: "Desenvolvimento Ombro", categoria: "Classic", foto: "assets/images/produtos/pro/classic_desenvolvimento_ombro.jpg" },
  { id: 98, nome: "Remada Baixa", categoria: "Classic", foto: "assets/images/produtos/pro/classic_remada_baixa.jpg" },
  { id: 99, nome: "Remada", categoria: "Classic", foto: "assets/images/produtos/pro/classic_remada.jpg" },
  { id: 100, nome: "Scott Máquina", categoria: "Classic", foto: "assets/images/produtos/pro/classic_scott_maquina.jpg" },
  { id: 101, nome: "Tríceps", categoria: "Classic", foto: "assets/images/produtos/pro/classic_triceps.jpg" },
  { id: 102, nome: "Abdominal", categoria: "Classic", foto: "assets/images/produtos/pro/classic_abdominal.jpg" },
  { id: 103, nome: "Lombar", categoria: "Classic", foto: "assets/images/produtos/pro/classic_lombar.jpg" },
  { id: 104, nome: "Leg Press Horizontal", categoria: "Classic", foto: "assets/images/produtos/pro/classic_leg_press_horizontal.jpg" },
  { id: 105, nome: "Cadeira Extensora", categoria: "Classic", foto: "assets/images/produtos/pro/classic_cadeira_extensora.jpg" },
  { id: 106, nome: "Cadeira Flexora", categoria: "Classic", foto: "assets/images/produtos/pro/classic_cadeira_flexora.jpg" },
  { id: 107, nome: "Mesa Flexora", categoria: "Classic", foto: "assets/images/produtos/pro/classic_mesa_flexora.jpg" },
  { id: 108, nome: "Abdutora", categoria: "Classic", foto: "assets/images/produtos/pro/classic_abdutora.jpg" },
  { id: 109, nome: "Adutora", categoria: "Classic", foto: "assets/images/produtos/pro/classic_adutora.jpg" },
  { id: 110, nome: "Panturrilha", categoria: "Classic", foto: "assets/images/produtos/pro/classic_panturrilha.jpg" },
  { id: 111, nome: "Glúteo", categoria: "Classic", foto: "assets/images/produtos/pro/classic_gluteo.jpg" },
  { id: 112, nome: "Peitoral Fly Dorsal", categoria: "Classic", foto: "assets/images/produtos/pro/classic_peitoral_fly_dorsal.jpg" },
  { id: 113, nome: "Puxador Costas", categoria: "Classic", foto: "assets/images/produtos/pro/classic_puxador_costas.jpg" },
  { id: 114, nome: "Gráviton", categoria: "Classic", foto: "assets/images/produtos/pro/classic_graviton.jpg" },

  // ── PRO · PLATE LOAD ─────────────────────────────────
  { id: 115, nome: "Supino Reto", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_supino_reto.jpg" },
  { id: 116, nome: "Supino Inclinado", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_supino_inclinado.jpg" },
  { id: 117, nome: "Supino Declinado", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_supino_declinado.jpg" },
  { id: 118, nome: "Agachamento Articulado", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_agachamento_articulado.jpg" },
  { id: 119, nome: "Supino Guiado", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_supino_guiado.jpg" },
  { id: 120, nome: "Bíceps", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_biceps.jpg" },
  { id: 121, nome: "Tríceps", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_triceps.jpg" },
  { id: 122, nome: "Peitoral Articulado Inclinado", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_peitoral_articulado_inclinado.jpg" },
  { id: 123, nome: "Desenvolvimento", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_desenvolvimento.jpg" },
  { id: 124, nome: "Abdominal Articulado", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_abdominal_articulado.jpg" },
  { id: 125, nome: "Remada Baixa", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_remada_baixa.jpg" },
  { id: 126, nome: "Remada Inclinada Linear", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_remada_inclinada_linear.jpg" },
  { id: 127, nome: "Puxada Alta", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_puxada_alta.jpg" },
  { id: 128, nome: "Remada", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_remada.jpg" },
  { id: 129, nome: "Puxada Alta com Supino", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_puxada_alta_com_supino.jpg" },
  { id: 130, nome: "Pullover", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_pullover.jpg" },
  { id: 131, nome: "Leg Press 45°", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_leg_press_45.jpg" },
  { id: 132, nome: "Cadeira Extensora", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_cadeira_extensora.jpg" },
  { id: 133, nome: "Flexora em Pé", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_flexora_em_pe.jpg" },
  { id: 134, nome: "Abdutora", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_abdutora.jpg" },
  { id: 135, nome: "Leg Press 90°", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_leg_press_90.jpg" },
  { id: 136, nome: "Leg Press Unilateral", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_leg_press_unilateral.jpg" },
  { id: 137, nome: "Agachamento Sumo", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_agachamento_sumo.jpg" },
  { id: 138, nome: "Panturrilha Sentada", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_panturrilha_sentada.jpg" },
  { id: 139, nome: "Glúteo", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_gluteo.jpg" },
  { id: 140, nome: "Panturrilha em Pé", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_panturrilha_em_pe.jpg" },
  { id: 141, nome: "Levantamento Terra Olímpico", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_levantamento_terra_olimpico.jpg" },
  { id: 142, nome: "Agachamento Sissy", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_agachamento_sissy.jpg" },
  { id: 143, nome: "Elevação Pélvica em Pé", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_elevacao_pelvica_em_pe.jpg" },
  { id: 144, nome: "Gaiola Agachamento", categoria: "Plate Load", foto: "assets/images/produtos/pro/pl_gaiola_agachamento.jpg" },

  // ── PRO · TITANIUM ───────────────────────────────────
  { id: 145, nome: "Supino Inclinado", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_supino_inclinado.jpg" },
  { id: 146, nome: "Supino Reto", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_supino_reto.jpg" },
  { id: 147, nome: "Deltoide", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_deltoide.jpg" },
  { id: 148, nome: "Peitoral Dorsal", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_peitoral_dorsal.jpg" },
  { id: 149, nome: "Desenvolvimento Ombro", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_desenvolvimento_ombro.jpg" },
  { id: 150, nome: "Puxador", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_puxador.jpg" },
  { id: 151, nome: "Remada Baixa", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_remada_baixa.jpg" },
  { id: 152, nome: "Remada", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_remada.jpg" },
  { id: 153, nome: "Scott Máquina", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_scott_maquina.jpg" },
  { id: 154, nome: "Tríceps Paralela", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_triceps_paralela.jpg" },
  { id: 155, nome: "Tríceps Testa", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_triceps_testa.jpg" },
  { id: 156, nome: "Tríceps", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_triceps.jpg" },
  { id: 157, nome: "Abdominal", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_abdominal.jpg" },
  { id: 158, nome: "Lombar", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_lombar.jpg" },
  { id: 159, nome: "Gráviton", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_graviton.jpg" },
  { id: 160, nome: "Leg Press Horizontal", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_leg_press_horizontal.jpg" },
  { id: 161, nome: "Cadeira Extensora", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_cadeira_extensora.jpg" },
  { id: 162, nome: "Cadeira Flexora", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_cadeira_flexora.jpg" },
  { id: 163, nome: "Mesa Flexora", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_mesa_flexora.jpg" },
  { id: 164, nome: "Cadeira Abdutora", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_cadeira_abdutora.jpg" },
  { id: 165, nome: "Cadeira Adutora", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_cadeira_adutora.jpg" },
  { id: 166, nome: "Apolete", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_apolete.jpg" },
  { id: 167, nome: "Glúteo", categoria: "Titanium", foto: "assets/images/produtos/pro/tit_gluteo.jpg" },

  // ── PRO · STATION ────────────────────────────────────
  { id: 168, nome: "Banco Reto com Suporte", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_reto_com_suporte.jpg" },
  { id: 169, nome: "Banco Inclinado", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_inclinado.jpg" },
  { id: 170, nome: "Banco Declinado com Suporte", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_declinado.jpg" },
  { id: 171, nome: "Banco Desenvolvimento", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_desenvolvimento.jpg" },
  { id: 172, nome: "Banco Bíceps", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_biceps.jpg" },
  { id: 173, nome: "Banco Lombar", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_lombar.jpg" },
  { id: 174, nome: "Abdominal Vertical", categoria: "Station", foto: "assets/images/produtos/pro/st_abdominal_vertical.jpg" },
  { id: 175, nome: "Agachamento Livre", categoria: "Station", foto: "assets/images/produtos/pro/st_agachamento_livre.jpg" },
  { id: 176, nome: "Gaiola Agachamento", categoria: "Station", foto: "assets/images/produtos/pro/st_gaiola_agachamento.jpg" },
  { id: 177, nome: "Gaiola Agachamento Completa", categoria: "Station", foto: "assets/images/produtos/pro/st_gaiola_agachamento_completa.jpg" },
  { id: 178, nome: "Banco 0-90°", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_0_90.jpg" },
  { id: 179, nome: "Banco Reto", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_reto.jpg" },
  { id: 180, nome: "Banco Declinado", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_declinado2.jpg" },
  { id: 181, nome: "Banco 90°", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_90.jpg" },
  { id: 182, nome: "Suporte Anilha", categoria: "Station", foto: "assets/images/produtos/pro/st_suporte_anilha.jpg" },
  { id: 183, nome: "Suporte Barra", categoria: "Station", foto: "assets/images/produtos/pro/st_suporte_barra.jpg" },
  { id: 184, nome: "Cross Angular", categoria: "Station", foto: "assets/images/produtos/pro/st_cross_angular.jpg" },
  { id: 185, nome: "Voador em Pé", categoria: "Station", foto: "assets/images/produtos/pro/st_voador_em_pe.jpg" },
  { id: 186, nome: "Crucifixo Anilhado", categoria: "Station", foto: "assets/images/produtos/pro/st_crucifixo_anilhado.jpg" },
  { id: 187, nome: "Remada Cavalinho", categoria: "Station", foto: "assets/images/produtos/pro/st_remada_cavalinho.jpg" },
  { id: 188, nome: "Puxador Convergente", categoria: "Station", foto: "assets/images/produtos/pro/st_puxador_convergente.jpg" },
  { id: 189, nome: "Banco Romano Turbo", categoria: "Station", foto: "assets/images/produtos/pro/st_banco_romano_turbo.jpg" },
  { id: 190, nome: "Smith", categoria: "Station", foto: "assets/images/produtos/pro/st_smith.jpg" },
  { id: 191, nome: "Leg Press 45°", categoria: "Station", foto: "assets/images/produtos/pro/st_leg_press_45.jpg" },
  { id: 192, nome: "Leg Press 45° Duplo", categoria: "Station", foto: "assets/images/produtos/pro/st_leg_press_45_duplo.jpg" },
  { id: 193, nome: "Leg Press 45° Compacto", categoria: "Station", foto: "assets/images/produtos/pro/st_leg_press_45_compacto.jpg" },
  { id: 194, nome: "Panturrilha", categoria: "Station", foto: "assets/images/produtos/pro/st_panturrilha.jpg" },
  { id: 195, nome: "Hack Agachamento", categoria: "Station", foto: "assets/images/produtos/pro/st_hack_agachamento.jpg" },
  { id: 196, nome: "Hack 45°", categoria: "Station", foto: "assets/images/produtos/pro/st_hack_45.jpg" },
  { id: 197, nome: "Agachamento Pêndulo", categoria: "Station", foto: "assets/images/produtos/pro/st_agachamento_pendulo.jpg" },
  { id: 198, nome: "Elevação Pélvica 3D", categoria: "Station", foto: "assets/images/produtos/pro/st_elevacao_pelvica_3d.jpg" },
  { id: 199, nome: "Super Glúteo Anilhado", categoria: "Station", foto: "assets/images/produtos/pro/st_super_gluteo_anilhado.jpg" },
  { id: 200, nome: "Hiperextensão Revertido", categoria: "Station", foto: "assets/images/produtos/pro/st_hiperextensao_revertido.jpg" },
  { id: 201, nome: "Glúteo Máximo", categoria: "Station", foto: "assets/images/produtos/pro/st_gluteo_maximo.jpg" },

  // ── PRO · ACESSÓRIOS ─────────────────────────────────
  { id: 202, nome: "Kettlebell Rubber", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_kettlebell_rubber.jpg" },
  { id: 203, nome: "Dumbbell Rubber", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_dumbbell_rubber.jpg" },
  { id: 204, nome: "Anilha Rubber", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_anilha_rubber.jpg" },
  { id: 205, nome: "Barra W Montada Rubber", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_w_montada_rubber.jpg" },
  { id: 206, nome: "Barra Reta Montada Rubber", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_reta_montada_rubber.jpg" },
  { id: 207, nome: "Torre de Halter Sextavado Emborrachado", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_torre_halter_sextavado.jpg" },
  { id: 208, nome: "Banco Step Regulável", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_banco_step_regulavel.jpg" },
  { id: 209, nome: "Kit Puxadores Anatômicos com Suporte", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_kit_puxadores_anatomicos.jpg" },
  { id: 210, nome: "Dumbbell Emborrachado", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_dumbbell_emborrachado.jpg" },
  { id: 211, nome: "Halter Sextavado Rubber", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_halter_sextavado_rubber.jpg" },
  { id: 212, nome: "Step Aeróbico", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_step_aerobico.jpg" },
  { id: 213, nome: "Suporte para Halter 10 Pares", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_suporte_halter_10_pares.jpg" },
  { id: 214, nome: "Barra H Cromada com Presilha", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_h_cromada.jpg" },
  { id: 215, nome: "Barra Hexagonal Armadilha", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_hexagonal_armadilha.jpg" },
  { id: 216, nome: "Barra W Cromada com Presilha", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_w_cromada.jpg" },
  { id: 217, nome: "Barra Reta Cromada com Presilha", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_reta_cromada.jpg" },
  { id: 218, nome: "Barra de Porta", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_de_porta.jpg" },
  { id: 219, nome: "Barra de Porta Completa", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_barra_de_porta_completa.jpg" },
  { id: 220, nome: "Proteção para Barra", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_protecao_para_barra.jpg" },
  { id: 221, nome: "Anilha Emborrachada Olímpica", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_anilha_emborrachada_olimpica.jpg" },
  { id: 222, nome: "Anilha Basic Cement PS", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_anilha_basic_cement_ps.jpg" },
  { id: 223, nome: "Corda com Contador Digital", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_corda_contador_digital.jpg" },
  { id: 224, nome: "Boneco Bob", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_boneco_bob.jpg" },
  { id: 225, nome: "Roda de Exercícios", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_roda_exercicios.jpg" },
  { id: 226, nome: "Roda de Exercícios Abdominais", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_roda_exercicios_abdominais.jpg" },
  { id: 227, nome: "Colchonete Dobrável", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_colchonete_dobravel.jpg" },
  { id: 228, nome: "Trampolim", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_trampolim.jpg" },
  { id: 229, nome: "Kit Piso de Proteção", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_kit_piso_protecao.jpg" },
  { id: 230, nome: "Step Light", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_step_light.jpg" },
  { id: 231, nome: "Suporte Barra Olímpica", categoria: "Acessórios", foto: "assets/images/produtos/pro/ac_suporte_barra_olimpica.jpg" },

];
